// apps/web/src/features/docs/content/framework-nuxt.tsx
import { createFrameworkGuide } from './create-framework-guide';

export const NuxtGuidePage = createFrameworkGuide({
  framework: 'Nuxt',
  title: 'Use Voltbase with Nuxt',
  description:
    'Create a Voltbase project, add sample data, and query it from a Nuxt app.',
  createApp: {
    command: `npx nuxi@latest init voltbase-nuxt
cd voltbase-nuxt
npm install`,
  },
  env: {
    filename: '.env',
    code: `NUXT_PUBLIC_VOLTBASE_URL=https://YOUR_API/api/projects/YOUR_SLUG
NUXT_PUBLIC_VOLTBASE_ANON_KEY=your-anon-key`,
    tip: (
      <>
        Public runtime config is available on both server and client. Keep
        service role keys out of <code>NUXT_PUBLIC_*</code>.
      </>
    ),
  },
  client: {
    filename: 'composables/useVoltbase.ts',
    code: `import { createClient } from 'voltbase-js';

export function useVoltbase() {
  const config = useRuntimeConfig();
  return createClient(
    config.public.voltbaseUrl as string,
    config.public.voltbaseAnonKey as string,
  );
}`,
  },
  query: {
    filename: 'nuxt.config.ts + pages/index.vue',
    language: 'ts',
    intro: (
      <>
        Wire public config in <code>nuxt.config.ts</code>, then fetch in a page:
      </>
    ),
    code: `// nuxt.config.ts
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      voltbaseUrl: process.env.NUXT_PUBLIC_VOLTBASE_URL,
      voltbaseAnonKey: process.env.NUXT_PUBLIC_VOLTBASE_ANON_KEY,
    },
  },
});

// pages/index.vue
<script setup lang="ts">
const voltbase = useVoltbase();
const { data: instruments, error } = await voltbase
  .from('instruments')
  .select('id, name')
  .order('id', 'asc');
</script>

<template>
  <p v-if="error">{{ error.message }}</p>
  <ul v-else>
    <li v-for="row in instruments" :key="row.id">{{ row.name }}</li>
  </ul>
</template>`,
  },
});

// apps/web/src/features/docs/content/framework-vue.tsx
import { createFrameworkGuide } from './create-framework-guide';

export const VueGuidePage = createFrameworkGuide({
  framework: 'Vue',
  title: 'Use Voltbase with Vue',
  description:
    'Create a Voltbase project, add sample data, and query it from a Vite Vue app.',
  createApp: {
    command: `npm create vite@latest voltbase-vue -- --template vue-ts
cd voltbase-vue
npm install`,
  },
  env: {
    filename: '.env',
    code: `VITE_VOLTBASE_URL=https://YOUR_API/api/projects/YOUR_SLUG
VITE_VOLTBASE_ANON_KEY=your-anon-key`,
  },
  client: {
    filename: 'src/lib/voltbase.ts',
    code: `import { createClient } from 'voltbase-js';

export const voltbase = createClient(
  import.meta.env.VITE_VOLTBASE_URL,
  import.meta.env.VITE_VOLTBASE_ANON_KEY,
);`,
  },
  query: {
    filename: 'src/App.vue',
    language: 'ts',
    code: `<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { voltbase } from './lib/voltbase';

type Instrument = { id: number; name: string };

const rows = ref<Instrument[]>([]);
const error = ref<string | null>(null);

onMounted(async () => {
  const { data, error: err } = await voltbase
    .from('instruments')
    .select('id, name')
    .order('id', 'asc');
  if (err) error.value = err.message;
  else rows.value = (data as Instrument[]) ?? [];
});
</script>

<template>
  <p v-if="error">{{ error }}</p>
  <ul v-else>
    <li v-for="row in rows" :key="row.id">{{ row.name }}</li>
  </ul>
</template>`,
  },
});
