// apps/web/src/features/docs/content/framework-sveltekit.tsx
import { createFrameworkGuide } from './create-framework-guide';

export const SveltekitGuidePage = createFrameworkGuide({
  framework: 'SvelteKit',
  title: 'Use Voltbase with SvelteKit',
  description:
    'Create a Voltbase project, add sample data, and query it from a SvelteKit app.',
  createApp: {
    command: `npx sv create voltbase-sveltekit
cd voltbase-sveltekit
npm install`,
    note: 'Pick the TypeScript template when prompted.',
  },
  env: {
    filename: '.env',
    code: `PUBLIC_VOLTBASE_URL=https://YOUR_API/api/projects/YOUR_SLUG
PUBLIC_VOLTBASE_ANON_KEY=your-anon-key`,
    tip: (
      <>
        SvelteKit exposes <code>PUBLIC_*</code> vars to the browser via{' '}
        <code>$env/static/public</code>.
      </>
    ),
  },
  client: {
    filename: 'src/lib/voltbase.ts',
    code: `import { createClient } from 'voltbase-js';
import {
  PUBLIC_VOLTBASE_URL,
  PUBLIC_VOLTBASE_ANON_KEY,
} from '$env/static/public';

export const voltbase = createClient(
  PUBLIC_VOLTBASE_URL,
  PUBLIC_VOLTBASE_ANON_KEY,
);`,
  },
  query: {
    filename: 'src/routes/+page.server.ts',
    language: 'ts',
    intro: (
      <>
        Load data in a server <code>load</code> function, then render in the
        page:
      </>
    ),
    code: `// src/routes/+page.server.ts
import { voltbase } from '$lib/voltbase';
import type { PageServerLoad } from './$types';

export const load: PageServerLoad = async () => {
  const { data, error } = await voltbase
    .from('instruments')
    .select('id, name')
    .order('id', 'asc');

  if (error) throw new Error(error.message);
  return { instruments: data ?? [] };
};

// src/routes/+page.svelte
<script lang="ts">
  let { data } = $props();
</script>

<ul>
  {#each data.instruments as row}
    <li>{row.name}</li>
  {/each}
</ul>`,
  },
});

// apps/web/src/features/docs/content/framework-vue.tsx
import { createFrameworkGuide } from './create-framework-guide';

export const VueGuidePage = createFrameworkGuide({
  framework: 'Vue',
  title: 'Use Voltbase with Vue',
  description:
    'Create a Voltbase project, add sample data, and query it from a Vite Vue app.',
  createApp: {
    command: `npm create vite@latest voltbase-vue -- --template vue-ts
cd voltbase-vue
npm install`,
  },
  env: {
    filename: '.env',
    code: `VITE_VOLTBASE_URL=https://YOUR_API/api/projects/YOUR_SLUG
VITE_VOLTBASE_ANON_KEY=your-anon-key`,
  },
  client: {
    filename: 'src/lib/voltbase.ts',
    code: `import { createClient } from 'voltbase-js';

export const voltbase = createClient(
  import.meta.env.VITE_VOLTBASE_URL,
  import.meta.env.VITE_VOLTBASE_ANON_KEY,
);`,
  },
  query: {
    filename: 'src/App.vue',
    language: 'ts',
    code: `<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { voltbase } from './lib/voltbase';

type Instrument = { id: number; name: string };

const rows = ref<Instrument[]>([]);
const error = ref<string | null>(null);

onMounted(async () => {
  const { data, error: err } = await voltbase
    .from('instruments')
    .select('id, name')
    .order('id', 'asc');
  if (err) error.value = err.message;
  else rows.value = (data as Instrument[]) ?? [];
});
</script>

<template>
  <p v-if="error">{{ error }}</p>
  <ul v-else>
    <li v-for="row in rows" :key="row.id">{{ row.name }}</li>
  </ul>
</template>`,
  },
});
